# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:2

pipelines:
  default:
      - step:
          name: 'Initialisation of sbt'
          script:
              - apt-get update
              - apt-get install apt-transport-https
              - echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
              - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 642AC823
          - apt-get update
          - echo "Installing sbt ..."
          - apt-get install sbt   
      - step:
          name: 'Build and Test using sbt'
          script:
            - echo "Running 'sbt clean test' ..."
            - sbt clean test
#      - step:
#          name: 'Lint'
#          script:
#            - echo "Your linting goes here..."
#      - step:
#          name: 'Security scan'
#          script:
#            - echo "Your security scan goes here..."

    # The following deployment steps will be executed for each pipeline run. To configure your steps and conditionally deploy see https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/
#    - step:
#        name: 'Deployment to Staging'
#        deployment: staging
#        script:
#          - echo "Your deployment to staging script goes here..."
#    - step:
#        name: 'Deployment to Production'
#        deployment: production
#        trigger: 'manual'
#        script:
#          - echo "Your deployment to production script goes here..."
