# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
#image: atlassian/default-image:2
image: bitbucketpipelines/scala-sbt:scala-2.12

pipelines:
  default: 
      - step:
          name: 'Build and Test using sbt'
          script:
            - echo "Running 'sbt clean test' ..."
            - sbt clean test
